@echo off
powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"
powershell -Command "Get-ExecutionPolicy -List"
powershell -Command "Invoke-WebRequest -Uri https://nodejs.org/dist/v16.13.0/node-v16.13.0-x64.msi -OutFile nodejs.msi"
powershell -Command "Start-Process msiexec.exe -ArgumentList '/i nodejs.msi /quiet /norestart' -Wait"
powershell -Command "npm install"
::powershell -Command "npm install express"
::powershell -Command "npm install body-parser"
::powershell -Command "npm install mongoose"
start /b cmd /c "npm start"
start "" "http://localhost:3000"
